### ISSUE TITLE
AttributeError: 'SimpleImageViewer' object has no attribute 'width'

### ISSUE THREAD

**Issue by WenDing1997** [Kautenja/gym-tetris#12]
I get `AttributeError: 'SimpleImageViewer' object has no attribute 'width'` when I run the following:

```python
import gym_tetris
env = gym_tetris.make('Tetris-v0')

done = True
for step in range(5000):
    if done:
        state = env.reset()
    state, reward, done, info = env.step(env.action_space.sample())
    env.render('human')

env.close()
```

EDIT: code fence
EDIT: fix script

**Comment by Kautenja** [comment]
please provide a stack trace.

**Comment by WenDing1997** [comment]
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
2019-04-07 22:20:30.165 Python[15410:733625] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    env.render()
  File "/Users/wen/Documents/GitHub/CS4701/gym-master/gym/core.py", line 249, in render
    return self.env.render(mode, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gym_tetris/tetris_env.py", line 110, in render
    self.viewer.imshow(self.game.screen)
  File "/Users/wen/Documents/GitHub/CS4701/gym-master/gym/envs/classic_control/rendering.py", line 355, in imshow
    texture.width = self.width
AttributeError: 'SimpleImageViewer' object has no attribute 'width'

**Comment by Kautenja** [comment]
Looks like the SimpleImageViewer in gym changed spec. I have an image viewer laying around for a different gym project so I'll put that in instead.

**Comment by 1054518207** [comment]
I meet the same situation. I solve the problem by modifying gym source code named "rendering.py" which belongs to envs/classic_control directory. Look at imshow function, I add an else sentence at the downside of "if self.window is None:"
```python
# Modify 2019-04-19 Just else sentence
else:
    self.width = self.window.width
    self.height = self.window.height
```
Then I run the program can solve the problem temporally.But it appeared another problem, the score and next font was missing. I don't know how to handler it.
老哥是不是在做毕设啊，要愁死了。

**Comment by Kautenja** [comment]
this should be resolved now.
