### ISSUE TITLE
AttributeError: module 'pyglet.clock' has no attribute 'set_fps_limit'

### ISSUE THREAD

**Issue by Jaccccc** [Kautenja/gym-tetris#21]
When i put in the code: gym_tetris -e TetrisA-v2 -m human, or any other variation of that into the cmd, it gives the error message:

AttributeError: module 'pyglet.clock' has no attribute 'set_fps_limit'

I am on a raspberry pi 4 using raspbian.

Thanks!

**Comment by Kautenja** [comment]
no longer an issue, resolved with the latest version of nes-py

**Comment by Kautenja** [comment]
run: 

```shell
python3 -m pip install nes-py -U
```
