### ISSUE TITLE
Enviroment.observation_space prints multiple numbers 

### ISSUE THREAD

**Issue by Jaccccc** [Kautenja/gym-tetris#22]
In all of the q learning tutorials i have seen, when the enviroment.observation_space or enviroment.observation_space.n is printed, it returns a single digit, but in this environment, it returns 3. I am just a bit confused as to what to do here, whether or not i am printing the wrong variable or what, and this is my first time trying q learning, so any help would be greatly appreciated. Thanks!

The code:
from nes_py.wrappers import JoypadSpace
import gym_tetris
from gym_tetris.actions import MOVEMENT
import numpy as np

env = gym_tetris.make('TetrisA-v0')
enviroment = JoypadSpace(env, MOVEMENT)
enviroment.render()

print('Number of states: {}'.format(enviroment.observation_space))
print('Number of actions: {}'.format(enviroment.action_space))

the output:

Number of states: Box(240, 256, 3)
Number of actions: Discrete(12)

**Comment by Kautenja** [comment]
the observation space is a 3 dimensional tensor of pixels, i.e., an RGB image. _n_ represents the shape of the tensor. The first number is the height, the second is the width, and the third are the number of channels.

**Comment by Kautenja** [comment]
https://www.cs.toronto.edu/~vmnih/docs/dqn.pdf section 4.1 will explain more. I'd recommend reading the entire paper.
