### ISSUE TITLE
Ability to seed underlying game

### ISSUE THREAD

**Issue by jannesDoege** [Kautenja/gym-tetris#24]
### Is your feature request related to a problem? Please describe.

When first testing an algorithm it would be beneficial to have the ability of a fixed seed for the whole environmnet, i.e. primarily to fix the pieces which occur. Currently env.seed() seamingly only affects the python wrapper of the game, e.g. when calling env.action_spcace.sample(), and the desired outcome is not yet achievable by ways known to me.

### Describe the solution you'd like

A simple call to env.seed() should solve the issue.

### Describe alternatives you've considered

As I have no experience in emulation, my ability to come up with any solution on my own is nonexistent and thus I am also unable to determine whether my request is even accomplishable.

**Comment by Kautenja** [comment]
Ah, yes this would be good functionality to have. I don't recall how RNG works for this particular title but it might be a trivial fix. I'll take a look.

**Comment by Kautenja** [comment]
Fixed!
